### ISSUE TITLE
No dark mode support

### ISSUE THREAD

**Issue by snshn** [Lyrics/lyrics-website-generator#19]
Needs to have a switcher along with CSS (

    @media (prefers-color-scheme: dark) {
    }
)

**Comment by Dorson** [comment]
Yes, dark or gray colors for the users with the `prefers-color-scheme: dark` setting are great. That works on mobile devices with the latest browsers. The CSS variables for all CSS colors make this option easy to implement.

Recently, I coded the Dark Mode switch in CSS and basic Java Script.

In my version of the dark mode, we can have multiple color themes in one CSS file. Then set or remember color settings with one short JS function without logins.

**Try it** on the GitHub demo page :

https://dorson.github.io/CSS-Dark-Mode-and-color-switch/

Feel free to fork, copy, adopt, etc..

Have fun ! :+1:

**Comment by snshn** [comment]
Hey, I'll make sure to make use of it, thank you!

**Comment by snshn** [comment]
Used `prefers-color-scheme: dark` for now without JS, solves the problem but may add a manual switch later.
