### ISSUE TITLE
build.py looks for 'lyrics.git' but fails if the dir is named 'lyrics'

### ISSUE THREAD

**Issue by andy5995** [Lyrics/lyrics-website-generator#48]
Fails with this error:

```
Traceback (most recent call last):
  File "../build.py", line 264, in <module>
    for letter in sorted(next(os.walk(sourceDatabaseDir))[1]):
StopIteration
make: *** [Makefile:20: build] Error 1
```

I think there should be a check in build.py to use either 'lyrics' or 'lyrics.git' (i.e. If 'lyrics.git' doesn't exist, try 'lyrics').

https://github.com/Lyrics/lyrics-website-generator/blob/4e0dad3afcb49fba0090cd7d3728df47b4b200d7/build.py#L14

For me, 'make' failed because my repo was cloned without the '.git' extension (and most all of my repos don't have a .git extension).

Another option, though may not be suitable for the size of this project, would be to add the lyrics db to this repo as a git submodule (which I could help with).

**Comment by snshn** [comment]
That's totally my bad, I never got to make the source db path configurable, I'll do it now (could break the CI/CD for some time but oh well, gotta break a few eggs to make an omelet).

**Comment by andy5995** [comment]
Oh yeah, everything will turn out happily ever after in the end. :)

Oh, hey, thanks for starring my rmw project, @snshn !
