### ISSUE TITLE
No way to link to source text file

### ISSUE THREAD

**Issue by snshn** [Lyrics/lyrics-website-generator#61]
The database consists of well-formatted lightweight text files that contain both lyrics and metadata. This website builder parses them and creates HTML pages, but those pages don't link to the original source file. It could be done via raw.github.com or by copying files to lyrics.github.io (either without extension or with .txt extension, whatever is better/works). Then linking those files from underneath every lyrics page would let people view the source text file.

**Comment by defanor** [comment]
There was [a suggestion to add "edit on GitHub" links](https://github.com/Lyrics/lyrics/discussions/491), which would link the sources. Source files can also be linked with [link rel="alternate"](https://html.spec.whatwg.org/dev/links.html#rel-alternate) and/or [dc:source](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/source) (and similar relations, embedded via RDFa).

**Comment by snshn** [comment]
I'm not sure how many users would find that plaintext version linked via `rel="alternative"`, do browsers usually indicate there's an alternative version available?

**Comment by defanor** [comment]
> I'm not sure how many users would find that plaintext version linked via rel=
> "alternative", do browsers usually indicate there's an alternative version
> available?

At least Firefox doesn't seem to do that by default (well, it does allow
to select alternate stylesheets, and either used to handle RSS/Atom
feeds linked that way, or does that with an extension, but doesn't seem
to allow to switch between regular alternate document versions), and
neither does it handle RDFa.

I find it to be an okay solution for non-essential bits of metadata
though: that way they are included in a standard way, but without
cluttering a document.

I think it'd be too much to link both "edit on GitHub" and raw sources,
but maybe just GitHub pages corresponding to those files can be linked
instead, from which both in-browser editing and raw versions can be
accessed. And the line/range linking discussed recently would also be
available there.

**Comment by snshn** [comment]
The "edit on GitHub" button is in place, this can be considered closed
