### ISSUE TITLE
Including translations.

### ISSUE THREAD

**Issue by egecelikci** [Lyrics/lyrics-website-generator#65]
I am thinking of contributing to the database with translated lyrics, but this version of the site does not show the translations on the website, do we have a chance to support this?

I saw it has been asked in this issue, but the question remained unanswered:
> ### 3. Translations
> Looks like the /Lyrics repo has a translations folder but it doesn't seem to be supported at all by the site?
> [`https://github.com/Lyrics/lyrics.github.io/issues/15`](https://github.com/Lyrics/lyrics.github.io/issues/15)

**Comment by snshn** [comment]
Good day @egecelikci,

would love to have more translations, and yes, the site currently doesn't process them into HTML, there are only a couple right now in the database.

There are two discussions in the main repo, [this](https://github.com/Lyrics/lyrics/discussions/520) and [this](https://github.com/Lyrics/lyrics/discussions/535).

I'd like to approach it in agile fashion: first make the website generator create pages out of those translations, then link them from song pages, and then implement translation mapping when map is available. Please feel free to submit more translations right now, they will appear online once I enhance the generator.
